sudo: required
dist: trusty
language: node_js
node_js:
    - node
before_script:
    - npm install
    - npm i -g angular-cli-ghpages
script:
    - npm test
    - ng build --prod
deploy:
    - angular-cli-ghpages --repo=https://GH_TOKEN@github.com/dolan-bio/website.git --name="Travis CI"