sudo: required
dist: trusty
language: node_js
node_js:
    - node
before_script:
    - npm install
    - npm install angular-cli -g
script:
    - npm test
    - npm run tsc
deploy:
    - ng github-pages:deploy --message "Deploying to Github Pages"